export const subjectLinks = [
  {
    title: "Maths",
    inProgress: [
      { name: "Quadratic Equations & Expressions", percentage: 25 },
      { name: "Sets", percentage: 35 },
      { name: "Mathematical Induction", percentage: 25 },
      { name: "Linear Equations", percentage: 45 },
    ],
    startPractising: [
      {
        name: "Sets",
        percentage: 35,
        topics: 6,
        incorrect: 4,
        speed: 20,
        accuracy: 20,
      },
      {
        name: "Complex Numbers",
        percentage: 55,
        topics: 2,
        incorrect: 3,
        speed: 15,
        accuracy: 50,
      },
      {
        name: "Mathematical Induction",
        percentage: 63,
        topics: 8,
        incorrect: 2,
        speed: 10,
        accuracy: 20,
      },
      {
        name: "Quadratic Equations & Expressions",
        percentage: 25,
        topics: 8,
        incorrect: 7,
        speed: 20,
        accuracy: 25,
      },
    ],
  },
  {
    title: "Physics",
    inProgress: [
      { name: "Motion in a Straight Line", percentage: 25 },
      { name: "Current Electricity", percentage: 35 },
      { name: "Semiconductor Physics", percentage: 55 },
      { name: "Alternating Current", percentage: 25 },
    ],
    startPractising: [
      {
        name: "Current Electricity",
        percentage: 35,
        topics: 6,
        incorrect: 4,
        speed: 20,
        accuracy: 20,
      },
      {
        name: "Alternating Current",
        percentage: 60,
        topics: 7,
        incorrect: 3,
        speed: 15,
        accuracy: 50,
      },
      {
        name: "Electromagnetic Induction",
        percentage: 40,
        topics: 3,
        incorrect: 9,
        speed: 18,
        accuracy: 20,
      },
      {
        name: "Semiconductor Physics",
        percentage: 20,
        topics: 8,
        incorrect: 7,
        speed: 20,
        accuracy: 25,
      },
    ],
  },
  {
    title: "Chemistry",
    inProgress: [
      { name: "States of Matter", percentage: 25 },
      { name: "Electrochemistry", percentage: 45 },
      { name: "Organic Chemistry", percentage: 55 },
      { name: "Kinetic theory of Gases", percentage: 45 },
    ],
    startPractising: [
      {
        name: "States of Matter",
        percentage: 35,
        topics: 6,
        incorrect: 4,
        speed: 20,
        accuracy: 20,
      },
      {
        name: "Kinetic theory of Gases",
        percentage: 40,
        topics: 2,
        incorrect: 3,
        speed: 15,
        accuracy: 50,
      },
      {
        name: "Electrochemistry",
        percentage: 63,
        topics: 8,
        incorrect: 2,
        speed: 10,
        accuracy: 20,
      },
      {
        name: "Organic Chemistry",
        percentage: 35,
        topics: 8,
        incorrect: 7,
        speed: 20,
        accuracy: 25,
      },
    ],
  },
];

export const testCards = [
  {
    img: "dashboard-main-practice-papers-icon.svg",
    title: "Practice Papers",
    subtitle: "Practice chapter and topic wise questions",
    to: "/practicePapers",
  },
  {
    img: "dashboard-main-test-series-icon.svg",
    title: "Test Series",
    subtitle: "Provides you with the latest exam standards",
    to: "/testSeries",
  },
  {
    img: "dashboard-main-previous-papers-icon.svg",
    title: "Previous Papers",
    subtitle: "Evaluate your potential by performing previous papers",
    to: "/previousPapers",
  },
  {
    img: "dashboard-main-assignments-icon.svg",
    title: "Assignments",
    subtitle: "Monitor your learning with various set of assignments ",
    to: "/assignmentChapters",
  },
  {
    img: "dashboard-main-preparatory-tests-icon.svg",
    title: "Preparatory Tests",
    subtitle: "helps you assess your competitive skills",
    to: "/preparatoryTests",
  },
];
