export const questionListData = [
  {
    number: 1,
    question:
      "Which of the following is not a well defined collection of objects?",
    options: [
      "The set of natural numbers.",
      "Rivers of India.",
      "Various kinds of Triangles.",
      "Five most renowned Mathematicians of the world",
    ],
    correctAnswer: "Various kinds of Triangles.",
    key: "A well defined set must have finite number of objects.",
    bookmarked: false,
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
    hint: "Required Set is: {4,5,6}  ",
  },
  {
    number: 2,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
    hint: "Required Set is: {4,5,6}  ",
  },
  {
    number: 3,
    question:
      "Write the solution set of the equation x^2 + x - 6 in roster form ",
    options: ["{2,-3}", "{-1,-2}", "{1,2}", "{-1,2}"],
    correctAnswer: "{2,-3}",
    key: "Some key.",
    bookmarked: false,
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
    hint: "Required Set is: {4,5,6}  ",
  },
  {
    number: 4,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
    hint: "Required Set is: {4,5,6}  ",
  },
  {
    number: 5,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
    hint: "Required Set is: {4,5,6}  ",
  },
  {
    number: 6,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
    hint: "Required Set is: {4,5,6}  ",
  },
  {
    number: 7,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
    hint: "Required Set is: {4,5,6}  ",
  },
  {
    number: 8,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
    hint: "Required Set is: {4,5,6}  ",
  },
  {
    number: 9,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
    hint: "Required Set is: {4,5,6}  ",
  },
];
