export const questionListData = [
  {
    number: 1,
    question:
      "Which of the following is not a well defined collection of objects?",
    options: [
      "The set of natural numbers.",
      "Rivers of India.",
      "Various kinds of Triangles.",
      "Five most renowned Mathematicians of the world",
    ],
    correctAnswer: "Various kinds of Triangles.",
    key: "A well defined set must have finite number of objects.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 2,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 3,
    question:
      "Write the solution set of the equation x^2 + x - 6 in roster form ",
    options: ["{2,-3}", "{-1,-2}", "{1,2}", "{-1,2}"],
    correctAnswer: "{2,-3}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 4,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 5,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 6,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 7,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 8,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 9,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 10,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 11,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 12,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 13,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 14,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 15,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 16,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 17,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 18,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 19,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 20,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "maths",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 21,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 22,
    question:
      "Which of the following is not a well defined collection of objects?",
    options: [
      "The set of natural numbers.",
      "Rivers of India.",
      "Various kinds of Triangles.",
      "Five most renowned Mathematicians of the world",
    ],
    correctAnswer: "Various kinds of Triangles.",
    key: "A well defined set must have finite number of objects.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 23,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 24,
    question:
      "Write the solution set of the equation x^2 + x - 6 in roster form ",
    options: ["{2,-3}", "{-1,-2}", "{1,2}", "{-1,2}"],
    correctAnswer: "{2,-3}",
    key: "Some key.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 25,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 26,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 27,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 28,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 29,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 30,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },

  {
    number: 31,
    question:
      "Which of the following is not a well defined collection of objects?",
    options: [
      "The set of natural numbers.",
      "Rivers of India.",
      "Various kinds of Triangles.",
      "Five most renowned Mathematicians of the world",
    ],
    correctAnswer: "Various kinds of Triangles.",
    key: "A well defined set must have finite number of objects.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 32,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 33,
    question:
      "Write the solution set of the equation x^2 + x - 6 in roster form ",
    options: ["{2,-3}", "{-1,-2}", "{1,2}", "{-1,2}"],
    correctAnswer: "{2,-3}",
    key: "Some key.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 34,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 35,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "chemistry",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 36,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 37,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 38,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 39,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 40,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 41,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 42,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 43,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 44,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 45,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 46,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 47,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 48,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 49,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
  {
    number: 50,
    question:
      "Let X = {1,2,3,4,5,6}. If n represents any member of X, then roster form of n->x but 2n->x",
    options: ["{2,3,5,6}", "{5,6}", "{4,5,6}", "{3}"],
    correctAnswer: "{4,5,6}",
    key: "Some key.",
    bookmarked: false,
    subject: "physics",
    status: "unvisited",
    solution: "Required Set is: {4,5,6}  ",
  },
];
