export const liveLecturesData = [
  {
    chapter: "Binomial Theorem",
    publishDate: "10/12/2021",
    category: "Live",
    subject: "Maths",
    id: "1",
  },
  {
    chapter: "Electric Charges & Fields",
    publishDate: "10/12/2021",
    category: "Upcoming",
    subject: "Physics",
    id: "2",
  },
  {
    chapter: "Group Elements",
    publishDate: "10/12/2021",
    category: "Live",
    subject: "Chemistry",
    id: "3",
  },
  {
    chapter: "Solid State",
    publishDate: "10/12/2021",
    category: "Upcoming",
    subject: "Chemistry",
    id: "4",
  },
  {
    chapter: "Binomial Theorem",
    publishDate: "10/12/2021",
    category: "Live",
    subject: "Maths",
    id: "5",
  },
  {
    chapter: "Electric Charges & Fields",
    publishDate: "10/12/2021",
    category: "Upcoming",
    subject: "Physics",
    id: "6",
  },
  {
    chapter: "Binomial Theorem",
    publishDate: "10/12/2021",
    category: "Upcoming",
    subject: "Maths",
    id: "7",
  },
  {
    chapter: "Solid State",
    publishDate: "10/12/2021",
    category: "Upcoming",
    subject: "Chemistry",
    id: "8",
  },
  {
    chapter: "Binomial Theorem",
    publishDate: "10/12/2021",
    category: "Upcoming",
    subject: "Maths",
    id: "9",
  },
  {
    chapter: "Electric Charges & Fields",
    publishDate: "10/12/2021",
    category: "Upcoming",
    subject: "Physics",
    id: "10",
  },
  {
    chapter: "Binomial Theorem",
    publishDate: "10/12/2021",
    category: "Upcoming",
    subject: "Maths",
    id: "11",
  },
  {
    chapter: "Electric Charges & Fields",
    publishDate: "10/12/2021",
    category: "Upcoming",
    subject: "Physics",
    id: "12",
  },
];
