export const testsBoardData = [
  {
    testName:
      "Lorem ipsum dolor sit amet, consectetur adipiscingLorem ipsum dolor sit amet, consectetur adipiscing...",
    examType: "JEE - ADVANCED",
    testType: "Test Series",
    status: "Under Review",
    id: "1",
  },
  {
    testName: "Lorem ipsum dolor sit amet, consectetur adipiscing...",
    examType: "JEE - MAINS",
    testType: "Preparatory Test",
    status: "Approved",
    id: "2",
  },
  {
    testName: "Lorem ipsum dolor sit amet, consectetur adipiscing...",
    examType: "JEE - ADVANCED",
    testType: "Test Series",
    status: "Under Review",
    id: "3",
  },
  {
    testName: "Lorem ipsum dolor sit amet, consectetur adipiscing...",
    examType: "JEE - MAINS",
    testType: "Preparatory Test",
    status: "Approved",
    id: "4",
  },
  {
    testName: "Lorem ipsum dolor sit amet, consectetur adipiscing...",
    examType: "JEE - ADVANCED",
    testType: "Test Series",
    status: "Under Review",
    id: "5",
  },
  {
    testName: "Lorem ipsum dolor sit amet, consectetur adipiscing...",
    examType: "JEE - MAINS",
    testType: "Preparatory Test",
    status: "Approved",
    id: "6",
  },
  {
    testName: "Lorem ipsum dolor sit amet, consectetur adipiscing...",
    examType: "JEE - MAINS",
    testType: "Preparatory Test",
    status: "Under Review",
    id: "7",
  },
  {
    testName: "Lorem ipsum dolor sit amet, consectetur adipiscing...",
    examType: "JEE - MAINS",
    testType: "Test Series",
    status: "Approved",
    id: "8",
  },
  {
    testName: "Lorem ipsum dolor sit amet, consectetur adipiscing...",
    examType: "JEE - MAINS",
    testType: "Test Series",
    status: "Under Review",
    id: "9",
  },
  {
    testName: "Lorem ipsum dolor sit amet, consectetur adipiscing...",
    examType: "JEE - MAINS",
    testType: "Test Series",
    status: "Approved",
    id: "10",
  },
  {
    testName: "Lorem ipsum dolor sit amet, consectetur adipiscing...",
    examType: "JEE - MAINS",
    testType: "Test Series",
    status: "Under Review",
    id: "11",
  },
  {
    testName: "Lorem ipsum dolor sit amet, consectetur adipiscing...",
    examType: "JEE - MAINS",
    testType: "Test Series",
    status: "Approved",
    id: "12",
  },
];
